"use client";

import React, { useEffect, useState } from 'react';
import Link from 'next/link';
import { useDeckStore } from '@/store/deckStore';
import { GraduationCap, ArrowRight, BookOpen } from 'lucide-react';

export default function CoursesListPage() {
  const { decks } = useDeckStore();
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) return null;

  // Filter out any decks that might be pure flashcard decks instead of courses
  // In a full implementation we might have a flag `isCourse`. For MVP, we treat all generated decks here.
  const courseDecks = decks;

  return (
    <div className="max-w-5xl mx-auto space-y-8">
      <div className="flex flex-col md:flex-row gap-6 items-start md:items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2 flex items-center gap-3">
            <GraduationCap className="w-8 h-8 text-indigo-600" />
            My Courses
          </h1>
          <p className="text-gray-500 text-lg">
            Master complex topics through AI-generated structured skill trees.
          </p>
        </div>
        <Link
          href="/knowledge"
          className="px-5 py-2.5 bg-indigo-600 text-white font-semibold rounded-xl shadow-md hover:bg-indigo-700 transition-all flex items-center gap-2"
        >
          Generate New Course
        </Link>
      </div>

      {courseDecks.length === 0 ? (
        <div className="text-center py-20 bg-white rounded-3xl border border-dashed border-gray-300">
          <GraduationCap className="w-16 h-16 text-gray-300 mx-auto mb-4" />
          <h2 className="text-xl font-bold text-gray-900 mb-2">No courses yet</h2>
          <p className="text-gray-500 mb-6">Import a syllabus or book to generate your first learning path.</p>
          <Link href="/knowledge" className="text-indigo-600 font-semibold hover:underline">
            Go to Knowledge Forge &rarr;
          </Link>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {courseDecks.map((deck) => (
            <Link
              href={`/course?deckId=${deck.id}`}
              key={deck.id}
              className="group bg-white rounded-2xl p-6 shadow-sm border border-gray-100 hover:shadow-xl hover:-translate-y-1 transition-all duration-300 flex flex-col h-full relative overflow-hidden"
            >
              <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                <BookOpen className="w-24 h-24 text-indigo-600" />
              </div>

              <h3 className="text-xl font-bold text-gray-900 mb-2 z-10">{deck.title}</h3>
              <p className="text-gray-500 text-sm mb-6 flex-1 z-10">{deck.description || "A structured learning path generated by AI."}</p>

              <div className="flex items-center justify-between mt-auto z-10 pt-4 border-t border-gray-50">
                <span className="text-xs font-semibold text-gray-400 uppercase tracking-wider">
                  {new Date(deck.createdAt).toLocaleDateString()}
                </span>
                <span className="flex items-center text-indigo-600 font-semibold text-sm group-hover:text-indigo-800 transition-colors">
                  Enter Path <ArrowRight className="w-4 h-4 ml-1 group-hover:translate-x-1 transition-transform" />
                </span>
              </div>
            </Link>
          ))}
        </div>
      )}
    </div>
  );
}
